# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SavedResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, status: str=None, id: int=None):  # noqa: E501
        """SavedResponse - a model defined in Swagger

        :param code: The code of this SavedResponse.  # noqa: E501
        :type code: int
        :param status: The status of this SavedResponse.  # noqa: E501
        :type status: str
        :param id: The id of this SavedResponse.  # noqa: E501
        :type id: int
        """
        self.swagger_types = {
            'code': int,
            'status': str,
            'id': int
        }

        self.attribute_map = {
            'code': 'code',
            'status': 'status',
            'id': 'id'
        }

        self._code = code
        self._status = status
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'SavedResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SavedResponse of this SavedResponse.  # noqa: E501
        :rtype: SavedResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this SavedResponse.


        :return: The code of this SavedResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this SavedResponse.


        :param code: The code of this SavedResponse.
        :type code: int
        """

        self._code = code

    @property
    def status(self) -> str:
        """Gets the status of this SavedResponse.


        :return: The status of this SavedResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this SavedResponse.


        :param status: The status of this SavedResponse.
        :type status: str
        """

        self._status = status

    @property
    def id(self) -> int:
        """Gets the id of this SavedResponse.

        id of {created/edited} {run/route/group}  # noqa: E501

        :return: The id of this SavedResponse.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this SavedResponse.

        id of {created/edited} {run/route/group}  # noqa: E501

        :param id: The id of this SavedResponse.
        :type id: int
        """

        self._id = id
