# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UnauthorizedResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, detail: str=None):  # noqa: E501
        """UnauthorizedResponse - a model defined in Swagger

        :param detail: The detail of this UnauthorizedResponse.  # noqa: E501
        :type detail: str
        """
        self.swagger_types = {
            'detail': str
        }

        self.attribute_map = {
            'detail': 'detail'
        }

        self._detail = detail

    @classmethod
    def from_dict(cls, dikt) -> 'UnauthorizedResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UnauthorizedResponse of this UnauthorizedResponse.  # noqa: E501
        :rtype: UnauthorizedResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail(self) -> str:
        """Gets the detail of this UnauthorizedResponse.


        :return: The detail of this UnauthorizedResponse.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail: str):
        """Sets the detail of this UnauthorizedResponse.


        :param detail: The detail of this UnauthorizedResponse.
        :type detail: str
        """

        self._detail = detail
