# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserIdResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: int=None, profile_id: int=None):  # noqa: E501
        """UserIdResponse - a model defined in Swagger

        :param user_id: The user_id of this UserIdResponse.  # noqa: E501
        :type user_id: int
        :param profile_id: The profile_id of this UserIdResponse.  # noqa: E501
        :type profile_id: int
        """
        self.swagger_types = {
            'user_id': int,
            'profile_id': int
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'profile_id': 'profile_id'
        }

        self._user_id = user_id
        self._profile_id = profile_id

    @classmethod
    def from_dict(cls, dikt) -> 'UserIdResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserIdResponse of this UserIdResponse.  # noqa: E501
        :rtype: UserIdResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this UserIdResponse.


        :return: The user_id of this UserIdResponse.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this UserIdResponse.


        :param user_id: The user_id of this UserIdResponse.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def profile_id(self) -> int:
        """Gets the profile_id of this UserIdResponse.


        :return: The profile_id of this UserIdResponse.
        :rtype: int
        """
        return self._profile_id

    @profile_id.setter
    def profile_id(self, profile_id: int):
        """Sets the profile_id of this UserIdResponse.


        :param profile_id: The profile_id of this UserIdResponse.
        :type profile_id: int
        """

        self._profile_id = profile_id
